export const theme = {
  colors: {
    primary: '#00C7BE',
    primaryDark: '#00B3AA',
    secondary: '#FF6B6B',
    accent: '#4ECDC4',
    background: '#FFFFFF',
    backgroundDark: '#1A1A1A',
    surface: '#F8F9FA',
    surfaceDark: '#2D2D2D',
    text: '#2D3748',
    textDark: '#FFFFFF',
    textSecondary: '#718096',
    textLight: '#A0AEC0',
    success: '#48BB78',
    warning: '#ED8936',
    error: '#F56565',
    overlay: 'rgba(0, 0, 0, 0.5)',
    border: '#E2E8F0',
    borderDark: '#4A5568',
  },
  typography: {
    fontFamily: {
      regular: 'Inter-Regular',
      medium: 'Inter-Medium',
      semiBold: 'Inter-SemiBold',
      bold: 'Inter-Bold',
    },
    fontSize: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 18,
      xl: 20,
      '2xl': 24,
      '3xl': 28,
      '4xl': 32,
      '5xl': 36,
    },
    lineHeight: {
      tight: 1.2,
      normal: 1.5,
      relaxed: 1.75,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    '2xl': 48,
    '3xl': 64,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  elevation: {
    low: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    high: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      shadowOpacity: 0.2,
      elevation: 12,
    },
  },
} as const;
